name: Wordpress Deployment
run-name: ${{ github.actor }} is running Wordpress Deployment
on:
  # Manual Trigger
  workflow_dispatch:
  push:
    paths:
      - '*/**'
  pull_request:
    branches : [ main ]
defaults:
  run:
    shell: bash
permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
jobs:
  terraform:
    name: terraform validate
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::495425695747:instance-profile/terraform_role
          aws-region: eu-west-2

      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform-wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
