name: Deploy WordPress Terraform Infrastructure
run-name: ${{ github.actor }} is running WordPress Deployment...
on: [push]
jobs:
  terraform_deployment:
    runs-on: ubuntu-latest
    name: Validate Teraform Code

    steps:
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Validate
        id: fmt
        run: terraform fmt -check
          - run: echo ${{ steps.plan.outputs.stdout }}
          - run: echo ${{ steps.plan.outputs.stderr }}
          - run: echo ${{ steps.plan.outputs.exitcode }}
        continue-on-error: true

      - name: Terraform Initialise
        id: init
        run: terraform init
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
